[03/May/2016 11:48:13] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x03628950>.
[03/May/2016 11:49:38] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x03628950>.
[03/May/2016 12:23:13] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[03/May/2016 12:23:13] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[03/May/2016 12:23:18] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:23:18] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:23:18] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:23:18] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:23:18] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:23:19] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:23:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:23:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:36:57] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:37:01] WARNING [django.request:170] Not Found: /test
[03/May/2016 12:41:13] WARNING [django.request:170] Not Found: /test
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:41:19] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:42:45] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x03A2A8D0>.
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.8ab04c3cc212.css
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/css/stylish-portfolio.8b6327a7756a.css
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/css/main.85e24c7b0d94.css
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/font-awesome/css/font-awesome.min.feda974a77ea.css
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/js/jquery.3c9137d88a00.js
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.8c237312864d.js
[03/May/2016 12:47:16] WARNING [django.request:170] Not Found: /static/images/vaffelbandy_603x532_trans.ad3b4cdd46f0.png
[03/May/2016 12:47:17] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-16x16.64e3ff9a0dc3.png
[03/May/2016 12:47:17] WARNING [django.request:170] Not Found: /static/images/favicons/android-chrome-192x192.8df7f00901ed.png
[03/May/2016 12:47:17] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-96x96.428ea393f5b1.png
[03/May/2016 12:47:17] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-194x194.f59f63a8497b.png
[03/May/2016 12:47:17] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-32x32.cf103737e7c4.png
[03/May/2016 12:47:47] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.8ab04c3cc212.css
[03/May/2016 12:47:48] WARNING [django.request:170] Not Found: /static/css/stylish-portfolio.8b6327a7756a.css
[03/May/2016 12:47:48] WARNING [django.request:170] Not Found: /static/css/main.85e24c7b0d94.css
[03/May/2016 12:47:48] WARNING [django.request:170] Not Found: /static/font-awesome/css/font-awesome.min.feda974a77ea.css
[03/May/2016 12:47:48] WARNING [django.request:170] Not Found: /static/js/jquery.3c9137d88a00.js
[03/May/2016 12:47:48] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.8c237312864d.js
[03/May/2016 12:47:48] WARNING [django.request:170] Not Found: /static/images/vaffelbandy_603x532_trans.ad3b4cdd46f0.png
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.8ab04c3cc212.css
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/css/stylish-portfolio.8b6327a7756a.css
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/css/main.85e24c7b0d94.css
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/js/jquery.3c9137d88a00.js
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/font-awesome/css/font-awesome.min.feda974a77ea.css
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.8c237312864d.js
[03/May/2016 12:48:13] WARNING [django.request:170] Not Found: /static/images/vaffelbandy_603x532_trans.ad3b4cdd46f0.png
[03/May/2016 12:48:17] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.8ab04c3cc212.css
[03/May/2016 12:48:18] WARNING [django.request:170] Not Found: /static/css/stylish-portfolio.8b6327a7756a.css
[03/May/2016 12:48:18] WARNING [django.request:170] Not Found: /static/css/main.85e24c7b0d94.css
[03/May/2016 12:48:18] WARNING [django.request:170] Not Found: /static/font-awesome/css/font-awesome.min.feda974a77ea.css
[03/May/2016 12:48:18] WARNING [django.request:170] Not Found: /static/js/jquery.3c9137d88a00.js
[03/May/2016 12:48:18] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.8c237312864d.js
[03/May/2016 12:48:18] WARNING [django.request:170] Not Found: /static/images/vaffelbandy_603x532_trans.ad3b4cdd46f0.png
[03/May/2016 12:49:21] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037D6950>.
[03/May/2016 12:52:59] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x0360DDF0>.
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = "\n            SELECT name, type FROM sqlite_master\n            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'\n            ORDER BY name" - PARAMS = (); args=None
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.001) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_team"."id", "website_team"."team_name", "website_team"."team_from", "website_team"."tournament_class", "website_team"."timestamp" FROM "website_team"' - PARAMS = (); args=()
[03/May/2016 12:53:31] DEBUG [django.db.backends:89] (0.000) QUERY = 'SELECT "website_tournamentstatus"."id", "website_tournamentstatus"."signup", "website_tournamentstatus"."pre_start", "website_tournamentstatus"."started" FROM "website_tournamentstatus"' - PARAMS = (); args=()
[03/May/2016 12:56:21] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/stylish-portfolio.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 12:56:42] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:00:58] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/stylish-portfolio.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:01:00] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/stylish-portfolio.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:02:26] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'font-awesome/css/font-awesome.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:02:41] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'font-awesome/css/font-awesome.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:02:59] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/favicons/apple-touch-icon-57x57.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:02:59] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/favicons/apple-touch-icon-57x57.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:03:53] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/favicons/apple-touch-icon-57x57.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:05:58] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/vaffelbandy_603x532_trans.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:05:59] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'images/vaffelbandy_603x532_trans.png' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:07:17] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'js/jquery.js' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:08:13] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'js/jquery.js' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:08:47] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.css/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/css/stylish-portfolio.css/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/css/main.css/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/font-awesome/css/font-awesome.min.css/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/js/jquery.js/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.js/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/images/vaffelbandy_603x532_trans.png/
[03/May/2016 13:08:48] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-16x16.png/
[03/May/2016 13:08:49] WARNING [django.request:170] Not Found: /static/images/favicons/android-chrome-192x192.png/
[03/May/2016 13:08:49] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-96x96.png/
[03/May/2016 13:08:49] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-194x194.png/
[03/May/2016 13:08:49] WARNING [django.request:170] Not Found: /static/images/favicons/favicon-32x32.png/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/css/bootstrap.min.css/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/css/stylish-portfolio.css/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/css/main.css/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/font-awesome/css/font-awesome.min.css/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/js/jquery.js/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/js/bootstrap.min.js/
[03/May/2016 13:08:52] WARNING [django.request:170] Not Found: /static/images/vaffelbandy_603x532_trans.png/
[03/May/2016 13:09:34] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
[03/May/2016 13:43:20] ERROR [django.request:256] Internal Server Error: /
Traceback (most recent call last):
  File "C:\Python34\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Tommy\PycharmProjects\Vaffelbandy\website\views.py", line 46, in home
    context_instance=RequestContext(request))
  File "C:\Python34\lib\site-packages\django\shortcuts.py", line 45, in render_to_response
    using=using)
  File "C:\Python34\lib\site-packages\django\template\loader.py", line 116, in render_to_string
    template_name, context, context_instance, dirs, dictionary)
  File "C:\Python34\lib\site-packages\django\template\engine.py", line 221, in render_to_string
    return t.render(context_instance)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 209, in render
    return self._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\template\loader_tags.py", line 135, in render
    return compiled_parent._render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 201, in _render
    return self.nodelist.render(context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 903, in render
    bit = self.render_node(node, context)
  File "C:\Python34\lib\site-packages\django\template\base.py", line 917, in render_node
    return node.render(context)
  File "C:\Python34\lib\site-packages\django\templatetags\static.py", line 105, in render
    url = self.url(context)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 16, in url
    return static(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\templatetags\staticfiles.py", line 9, in static
    return staticfiles_storage.url(path)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 131, in url
    hashed_name = self.stored_name(clean_name)
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 280, in stored_name
    cache_name = self.clean_name(self.hashed_name(name))
  File "C:\Python34\lib\site-packages\django\contrib\staticfiles\storage.py", line 94, in hashed_name
    (clean_name, self))
ValueError: The file 'css/bootstrap.min.css' could not be found with <whitenoise.django.GzipManifestStaticFilesStorage object at 0x037BA8B0>.
